#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: indy-did-networks
  description: indy-did-networks
  default_branch: main
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
